# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=true
org.gradle.daemon=false

# Project
version=1.6.0+26.1.x
group=com.thedeathlycow.novoatlas

# Common
mod_id=novoatlas
mod_name=NovoAtlas
mod_author=TheDeathlyCow
license=LGPL-3.0
description=A data-driven image based world generator for Minecraft.
credits=itsmiir (Original Atlas mod)
java_version=25
minecraft_version = 26.1.2
minecraft_version_range = [26.1,26.2)

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_loader_version = 0.19.2
fabric_version = 0.149.1+26.1.2

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.1.2.7-beta
neoforge_loader_version_range=[4,)

# Dependencies
twelvemonkeys_imageio_version = 3.12.0

# Integrations
terrablender_version = 1.21.11-21.11.0.0
