plugins {
    id 'multiloader-common'
    id 'org.relativitymc.neo-loom'
    id 'me.modmuss50.mod-publish-plugin'
    id 'datapack-builder'
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    // use this to get mixins and asm in the common module, do not use fabric classes in common!!!!!
    compileOnly "net.fabricmc:fabric-loader:${fabric_loader_version}"
    compileOnly "com.github.glitchfiend:TerraBlender-fabric:${terrablender_version}"

    List.of(
            "imageio-webp",
            "imageio-metadata",
            "imageio-core"
    ).forEach {
        implementation "com.twelvemonkeys.imageio:$it:${project.twelvemonkeys_imageio_version}"
    }

    List.of(
            "common-image",
            "common-io",
            "common-lang"
    ).forEach {
        implementation "com.twelvemonkeys.common:$it:${project.twelvemonkeys_imageio_version}"
    }
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
}

sourceSets.main.resources { srcDir project(":common").file("src/main/generated") }

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
    commonGeneratedResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava file("src/main/java")
    commonResources file("src/main/resources")
    commonGeneratedResources file("src/main/generated")
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'common')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant ->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'common')
            }
        }
    }
}

publishMods {
    type = BETA
    changelog = rootProject.file("./changelogs/${project.version}.md").text

    github {
        repository = "TheDeathlyCow/novoatlas"
        accessToken = providers.environmentVariable("RELEASE_GITHUB_TOKEN")
        commitish = "26.3.x"
        tagName = "${project.version}"

        displayName = "[26.3.x] NovoAtlas Example Datapacks ${project.version}"

        additionalFiles.from(project.extensions.datapackArchives)
    }
}
