plugins {
    id 'multiloader-common'
    id 'net.fabricmc.fabric-loom'
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    // use this to get mixins and asm in the common module, do not use fabric classes in common!!!!!
    compileOnly "net.fabricmc:fabric-loader:${fabric_loader_version}"
    compileOnly "com.github.glitchfiend:TerraBlender-fabric:${terrablender_version}"

    List.of(
            "imageio-webp",
            "imageio-metadata",
            "imageio-core"
    ).forEach {
        implementation "com.twelvemonkeys.imageio:$it:${project.twelvemonkeys_imageio_version}"
    }

    List.of(
            "common-image",
            "common-io",
            "common-lang"
    ).forEach {
        implementation "com.twelvemonkeys.common:$it:${project.twelvemonkeys_imageio_version}"
    }
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'common')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant ->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'common')
            }
        }
    }
}
