name: Publish Mod
on: [workflow_dispatch] # Manual trigger

jobs:
  curseforge-fabric:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/openjdk/jdk:21-ubuntu
      options: --user root
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: publish
        run: ./gradlew fabric:build fabric:publishCurseforge
        env:
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
  modrinth-fabric:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/openjdk/jdk:21-ubuntu
      options: --user root
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: publish
        run: ./gradlew fabric:build fabric:publishModrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
  curseforge-neoforge:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/openjdk/jdk:21-ubuntu
      options: --user root
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: publish
        run: ./gradlew neoforge:build neoforge:publishCurseforge
        env:
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
  modrinth-neoforge:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/openjdk/jdk:21-ubuntu
      options: --user root
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: publish
        run: ./gradlew neoforge:build neoforge:publishModrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
  github-datapack:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/openjdk/jdk:21-ubuntu
      options: --user root
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: publish
        run: ./gradlew build common:publishGithub
        env:
          MODRINTH_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}